config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

get'chiikawas/index'=>'chiikawas#index'
get'chiikawas/link'=>'chiikawas#link'
get'chiikawas/omikuzi'=>'chiikawas#omikuzi'
get'chiikawas/daikiti'=>'chiikawas#daikiti'
get'chiikawas/tyuukiti'=>'chiikawas#tyuukiti'
get'chiikawas/syoukiti'=>'chiikawas#syoukiti'
get'chiikawas/suekiti'=>'chiikawas#suekiti'
get'chiikawas/kiti'=>'chiikawas#kiti'
get'chiikawas/kyou'=>'chiikawas#kyou'
get'chiikawas/daikyou'=>'chiikawas#daikyou'
get'chiikawas/story'=>'chiikawas#story'
get'chiikawas/good'=>'chiikawas#good'

resources:topics
resources:topic2s
resources:topic3s
root "chiikawas#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/topic2.rb
class Topic2 < ApplicationRecord
end

app/models/topic3.rb
class Topic3 < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chiikawas_controller.rb
class ChiikawasController < ApplicationController
    def index
    end

    def link
    end

    def omikuzi
    end

    def daikiti
    end

    def tyuukiti
    end

    def syoukiti
    end

    def suekiti
    end

    def kiti
    end

    def kyou
    end

    def daikyou
    end

    def story
    end
    
    def good 
    end
end

app/controllers/topic2s_controller.rb
class Topic2sController < ApplicationController
    def index
    end
    def new
      @topic2 = Topic2.new
    end
    def show
      @topic2 = Topic2.find_by(id: params[:id])
      @topic3 = Topic3.new
    end
    def create
      @topic2 = Topic2.new(topic2_params)
      if @topic2.save
          flash[:notice] = "診断が完了しました"
          redirect_to topic2_path(@topic2.id)
      else
          redirect_to :action => "new"
      end
    end
  private
    def topic2_params
        params.require(:topic2).permit(:id, :question2)
    end
end

app/controllers/topic3s_controller.rb
class Topic3sController < ApplicationController
    def index
    end
    def new
      @topic3 = Topic3.new
    end
    def show
      @topic3 = Topic3.find_by(id: params[:id])
    end
    def create
      @topic3 = Topic3.new(topic3_params)
      if @topic3.save
          flash[:notice] = "診断が完了しました"
          redirect_to topic3_path(@topic3.id)
      else
          redirect_to :action => "new"
      end
    end
  private
    def topic3_params
        params.require(:topic3).permit(:id, :question3)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
def index
end
def new
  @topic = Topic.new
end
def show
  @topic = Topic.find_by(id: params[:id])
  @topic2 = Topic2.new
end
def create
  @topic = Topic.new(topic_params)
  if @topic.save
      flash[:notice] = "診断が完了しました"
      redirect_to topic_path(@topic.id)
  else
      redirect_to :action => "new"
  end
end
private
def topic_params
    params.require(:topic).permit(:id, :question)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chiikawas_helper.rb
module ChiikawasHelper
end

app/helpers/topic2s_helper.rb
module Topic2sHelper
end

app/helpers/topic3s_helper.rb
module Topic3sHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/chiikawas/daikiti.html.erb
<div class="gatya">
    <p class="tomato">大吉です！！</p>
    <%= image_tag 'daikiti.jpg',:size => '500x450' %> 
</div>
<p class="arice">最高な一日になりそう！今日一日ハッピーに過ごそう。</p>

app/views/chiikawas/daikyou.html.erb
<div class="gatya">
    <p class="tomato">大凶...。逆に運がいいかも？</p>
    <%= image_tag 'daikyou.jpg',:size => '450x400' %> <br>
</div>
<p class="arice">まあ、気にせずに楽しく過ごそう！！</p><br>

app/views/chiikawas/good.html.erb
<div class="usagi2">
<html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="example.css">
  <title>サンプルのサイト</title>
</head>
<body>
<!-- header -->
  <header>
  	<h1 class="headline">
      <a>ちいかわの見どころを紹介！</a>
    </h1>
    <ul class="nav-list">
      <li class="nav-list-item">
        <a>～これを見るとちいかわのイメージ変わるかも？～</a>
     
    </ul>
  </header>
</body>
</html>


<%= image_tag 'deza',:size => '300x280',class:"ugoira" %> 
<%= image_tag 'deza2.jpg',:size => '300x280',class:"ugoira2" %> 
<%= image_tag 'deza3.jpg',:size => '300x280',class:"ugoira3" %> 

<div class="toc-005">
    <div>
        目次ってコトっ！？
    </div>
    <ol>
        <li><a href="#">ちいかわ族について</a></li>
        <li>
            <a href="#">キメラ化とは？</a>
            <ol>
                <li><a href="#">モモンガの秘密</a></li>
                <li><a href="#">ちいかわの世界にある謎のおいしい食べ物たち</a></li>
            </ol>
        </li>
    </ol>
</div>

<div class="ribbon14-wrapper">
  <span class="ribbon14">★</span>
  <div>
  <p>1.ちいかわ族について</p>
  </div>
</div>
<div class="db">
<%= image_tag 'zoku.jpg',:size => '550x400',class:"pu" %>
<p class="sora2">ちいかわ、ハチワレ、うさぎのような"なんかちいさくてかわいい生き物"を
略してちいかわといいます！<br>
ちいかわ族には個体差があり、知能・身体能力・更には経済力までそれぞれ違うので、<br>
まるで人間社会と同じような社会の中で暮らしています！</p>
    </div>

<div class="balloon5">
  <div class="faceicon">
    <%= image_tag 'hukidasi6.jpg'%> <img~>
  </div>
  <div class="chatting">
    <div class="says">
      <p>フ!（ちいかわの笑い方）</p>
    </div>
  </div>
</div>
<div class="balloon5">
  <div class="faceicon">
    <%= image_tag 'hukidasi2.jpg'%> <img~>
  </div>
  <div class="chatting">
    <div class="says">
      <p>みーんな仲良しだよね！</p>
     </div>
    </div>
   </div>



<div class="h3">
  ハチワレはすごく貧乏！？
  </div>
<div class="cd">
<%= image_tag 'omosiro',:size => '550x400' ,class:"tama3"%>
<p class="sora2">実はハチワレはすごく貧乏なことが描写されています！この画像はちいかわとハチワレが、<br>
ハチワレの家でご飯を食べているシーン。ハチワレは洞窟の中で暮らしていて家を持っていません。
テーブルは段ボール、粗大ゴミがおいてあるのを見るとお金あげたくなっちゃいますよね笑</p>
</div>

<div class="ribbon14-wrapper">
  <span class="ribbon14">★</span>
  <div>
  <p>2.キメラ化とは？</p>
  </div>
</div>
<div class="db">
<%= image_tag 'kimera',:size => '550x400',class:"tama3" %>
<p class="sora2">ちいかわ達の当然変異でもあるキメラ化。<br>キメラ化とは、かわいい見た目のちいかわ達がモンスターになってしまうことをいいます。<br>
キメラ化し、モンスターになってしまうと二度とちいかわ族に戻ることができない恐ろしい現象なのです。<br>
</div>

<div class="h3">
  アイテムによりキメラ化する！？
  </div>
  <div class="for">
<%= image_tag 'kimera2',:size => '550x350',class:"satoru" %>

<div class="arrow">
</div>

<%= image_tag 'kimera3',:size => '500x350',class:"satoru2" %>
</div>

<p class="yuji">アニメでも描かれたシーン。うさぎがリサイクルショップで購入した謎のステッキにはなんでも願いを叶える力がありました。<br>
しかし、それを使用したハチワレとうさぎは恐ろしい怪物へと姿を変えてしまいます。<br>
残されたちいかわがステッキを破壊したことで、元の姿に戻ることができました。
</div>

<div class="balloon5">
  <div class="faceicon">
    <%= image_tag 'hukidasi1.jpg'%> <img~>
  </div>
  <div class="chatting">
    <div class="says">
      <p>うう...うわああ...</p>
    </div>
  </div>
</div>
<div class="balloon5">
  <div class="faceicon">
    <%= image_tag 'hukidasi3.jpg'%> <img~>
  </div>
  <div class="chatting">
    <div class="says">
      <p>この時はほんとどうなるかとおもった...</p>
     </div>
    </div>
   </div>

   <div class="ribbon14-wrapper">
  <span class="ribbon14">★</span>
  <div>
  <p>3.モモンガの秘密</p>
  </div>
</div>

<div class="db">
<%= image_tag 'momonga2.jpg',:size => '550x400',class:"tama3"%>
<p class="sora2">ずる賢くて生意気、わがままでありつつ可愛いところもある...。<br>
いつもみんなを困らせては、自由に動き回る破天荒な一面もあります。
そんな小悪魔的な存在のモモンガですが、実はすごい秘密が隠されているんです！</p>
</div>

<div class="h3">
  でかつよと体が入れ替わっている！？
  </div>

<div class="cd">
<%= image_tag 'momonga3.jpg',:size => '350x500',class:"tama2" %>
<p class="sora2">この画像をみて分かる通り、でかつよがモモンガに対し体を返せ！！と言っているのが分かると思います。<br>
そう、実はモモンガとでかつよは体が入れ替わっており、今いるモモンガはでかつよという衝撃的な展開なんです！
どうやって入れ替わってしまったのかはまだ不明・・・。でかつよ（ももんが）はいまどこに...？</p>
</div>

<div class="h4">
  こんなシーンも...
  </div>

<div class="megumi">
<%= image_tag 'momonga4.jpg',:size => '350x500' %>
<%= image_tag 'momonga5.jpg',:size => '350x500' %>
<p class="sora2">気になる人は漫画を読んでみてね！</p>
</div>


<div class="ribbon14-wrapper">
  <span class="ribbon14">★</span>
  <div>
  <p>4.謎のおいしい食べ物たち</p>
  </div>
</div>
<p class="h5">１，味噌汁の川ってコトっ！？</p>
<div class="cd">
<%= image_tag 'tabe.jpg',:size => '350x500',class:"tama2" %>
<p class="sora2">ちいかわの世界では味噌汁の川が流れているんです！衝撃ですよね...笑<br>
このシーンではくりまんじゅうが二日酔いを和らげるために味噌汁を飲みにきています。<br>
具は巨大しじみでとてもおいしそう。でもどこから湧いてきたんだろう。</p>
</div>

<p class="h5">２，大量のケチャップご飯ってコトっ！？</p>
<div class="db">
<%= image_tag 'tabe2.jpg',:size => '350x500',class:"tama2" %>
<p class="sora2">突然現れた謎の大量のケチャップご飯！！<br>
チキンライスとかではないのがまた面白い所ですね。<br>
私の推しのうさぎはアレンジをして、お子様ランチのように見立てている...！流石です！</p>
</div>

<p class="h5">３，そばってコトっ！？</p>
<div class="db">
<%= image_tag 'tabe3.jpg',:size => '350x500',class:"tama2" %>
<p class="sora2">地面に現れたのはつゆに浮いているそば！？私もこれを見て驚きました笑<br>
つゆだけとかそばだけならわかるけど、どっちも湧くのは親切ですね！<br>
どうやらみんなはわさびをつけて食べるそうです。あなたはわさびをつけてそばを食べますか？<br></p>
</div>

</div>

app/views/chiikawas/index.html.erb
<body> 
<%= image_tag 'haikei toppage.jpg', :size => '1200x2050',class:"ame"%>
<link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
<div style="position: relative; display:inline-block;">
<%= image_tag 'chiikawas_toppage.jpg',:size => '1200x650' %>
<div style="position: absolute; top: 0; left: 0; max-width: 100%; max-height: 100%; padding: 30px; text-align: left;">
<p class="egg">～ちいかわサイト～</p>
</div></div>

    
<h1 class="ribbon">
   <span class="ribbon-content">ようこそちいかわサイトへ</span>
</h1>
<div class= "usagi">
    <div class="characters">
        <p class="title">characters</p>      
        <%= link_to chiikawas_link_path do %>
            <%= image_tag 'Rectangle 9.jpg', :size => '250x300',class:"pa"%>
        <% end %>
        <p class="explain">キャラクター紹介はこちらから</p>
    </div>
    <div class="hachiware">    
        <p class="title">story</p>
        <%= link_to chiikawas_story_path do %>
            <%= image_tag 'Rectangle 16.jpg',:size => '250x300' ,class:"pa"%>
            <% end %>
            <p class="explain">ちいかわの世界観がわかるかもっ！？</P>
    </div>
    <div class="chiikawa">
        <p class="title">good point</p>
        <%= link_to chiikawas_good_path do %>
            <%= image_tag 'Rectangle 17.jpg',:size => '250x300' ,class:"pa"%>
            <% end %>
             <p class="explain">ここではちいかわの魅力が分かる!</P>
    </div>
</div>
    <div class="link">
    <p class="explain"> 画像をクリックしてね↑↑</p>
    <div class="sinndann">
    chiikawas characters
      </div>
    <div class="sindangazou"><br><br>
    <%= image_tag 'sindan.jpg',:size => '550x400' %>  <br>
                                                      <br>
</div>
<h1 class="ribbon">
<span class="ribbon-content">キャラクター診断する人はボタンを押してね！</span>
</h1>
    <%= link_to"TAP！",new_topic_path,class:"omi2" %><br><br>
    <%= link_to"今日の運勢を占おう", chiikawas_omikuzi_path,class:"omi" %>
    <div class="douga">
    <p>アニメ動画のリンクはこちらから↓↓</P>
    <a href="https://youtu.be/pbQQAwSQUX4">
    <%= image_tag 'douga1.jpg', :size => '83x78' %>
  </a>   
  <a href="https://youtu.be/i6d3K6ln-d4">
  <%= image_tag 'douga 2.jpg', :size => '83x78' %>
  </a>
  <a href="https://youtu.be/a7cwqxmn7rY">
  <%= image_tag 'douga3.jpg', :size => '83x78' %>
  </a>
  </div>
  <div class="omi3">
  <a href="https://www.anime-chiikawa.jp/">ちいかわ公式サイトはこちらから</a>
      </div>
  </body>

app/views/chiikawas/kiti.html.erb
<div class="gatya">
    <p class="tomato">吉です！！</p>
    <%= image_tag 'kiti.jpg',:size => '450x400' %> 
</div>
<p class="arice">いいことをするともっと運がよくなるかも！</p>

app/views/chiikawas/kyou.html.erb
<div class="gatya">
    <p class="tomato">凶...です。</p>
    <%= image_tag 'kyou.jpg',:size => '400x400' %> 
</div>
<p class="arice">こういう日はさ、好きなことをするのが一番！</p>

app/views/chiikawas/story.html.erb
<link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">


<html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="example.css">
  <title>サンプルのサイト</title>
</head>
<body>
<!-- header -->
  <header>
  	<h1 class="headline">
      <a>～謎が多いちいかわの世界について～</a>
    </h1>
    <ul class="nav-list">
      <li class="nav-list-item">
        
        </ul>
        </header>
      </body>
      </html>
    <div class="cd3"><br>
    <%= image_tag 'nazo.jpg', :size => '600x300',class:"nazo"%>
    <p class="sora">ちいかわ族以外にも種族は存在している。<br>
                画像のようなでかつよ族という危険種族がいる<br><br>
                彼らは日々ちいかわ族を捕食し生活している。<br></p>
        </div><br>
        <div class="box8">
    <p>ここでワンポイント<br>
    　　彼らには友好型と擬態型が存在している。<br>
    ・友好型 ちいかわ達に親しく接してくれる。危険ではない.<br>
    ・擬態型　親しいフリをしてちいかわ達に近づき、油断させたのち襲いかかってくる危険な存在。</p>
</div>




    <p class="tya">~労働編~</p><br>
    <p class="tya2">ちいかわの世界では労働は必須であり、労働をすることで報酬を得て生活をしている。
    労働内容は"草むしり" "討伐"がメインである。</p>

<div class="cd">
<%= image_tag 'roudou1.jpg',:size => '400x500',class:"tama2"%>
<p class="sora">この画像ではちいかわ達がどのような労働条件で働くか選択をしている。<br>
                このシーンではちいかわは草むしり選択し、汗を流しながら働いている。<br><br>
                鎧さんというキャラクターが、労働を強いる代わりに報酬を与えている。<br>
                未だに鎧さんというキャラクターは謎が多く、完全な味方なのか分からない。</p>
</div>
 
<div class="balloon5">
  <div class="faceicon">
    <%= image_tag 'hukidasi1.jpg'%> <img~>
  </div>
  <div class="chatting">
    <div class="says">
      <p>働きたくないよ...</p>
    </div>
  </div>
</div>
<div class="balloon5">
  <div class="faceicon">
    <%= image_tag 'hukidasi2.jpg'%> <img~>
  </div>
  <div class="chatting">
    <div class="says">
      <p>だめだよ！！働かざる者食うべからずだからね！</p>
     </div>
    </div>
   </div>
   <p class="tya3">"討伐とは"</p>
  
   <div class="tora">
   <%= image_tag 'toubatu1.jpg',:size => '800x500',class:"choco"%><br>
   ↑↑↑アニメの一部シーン
   </div>
   <div class="cd">
   <%= image_tag 'toubatu2.jpg',:size => '400x500',class:"tama2"%><br><br>
   <p class="sora">討伐の仕事ではちいかわ達はいつも命がけで戦っているが報酬はそこまで高くはない。<br>
                ちいかわは武器のさすまたを使い討伐を行っている。ちいかわの戦闘能力は高くない。<br><br>
                怪物たちはなんか小さくてかわいい生き物（ちいかわ達）を捕食対象としている。<br>
                なぜ怪物たちが湧き出てくるのかは未だ不明である。</p>
</div>

<div class="balloon5">
  <div class="faceicon">
    <%= image_tag 'hukidasi1.jpg'%> <img~>
  </div>
  <div class="chatting">
    <div class="says">
      <p>死ぬかとおもったーー！</p>
    </div>
  </div>
</div>
<div class="balloon5">
  <div class="faceicon">
    <%= image_tag 'hukidasi3.jpg'%> <img~>
  </div>
  <div class="chatting">
    <div class="says">
      <p>でもこれもランカーに入るためなんだよね、、！！</p>
     </div>
    </div>
   </div>

   <div class="balloon3-right-btm">
   POINT
 </div>
  <p class="ranka">ランカーとは？？</p>
  <div class="wa"><br>
  <%= image_tag 'ranka.jpg', :size => '600x300',class:"rako2"%>
  上位に入るとランカーになれる。現状の１位はラッコであり、現代最強ランカーである。<br>
  高難易度の依頼を受けることができるため、報酬の量もかなり多い。<br>
  ランカーになると武器に自分の顔が表示される。<br>うさぎはこれを狙っているためかマーカーで自分の顔を描いている。
  </div>

  <div class="h1">
  実際の討伐ではどうなんだろう？？
  </div>
  <div class="cd"><br><br>
  <%= image_tag 'toubatu3.jpg', :size => '400x600',class:"tama2"%>
  <p class="sora">ちいかわ、ハチワレ、うさぎが共同して討伐に向かった一部のシーン。
  でかつよ族は攻撃力が高く、しっぽに当たっただけでダメージをかなり受けてしまう。
  現状ではまだちいかわ達ではでかつよを討伐することはできない。</p>
  </div>

  


  <div class="cd2"><br><br>
  <p class="sora2">このシーンでの討伐は失敗。<br>
  うさぎの爆発棒により、でかつよ族を退けることには成功した。<br>
  失敗した後は、信号弾を出すことで撤退することができる。<br>
  しかし、このクレーンゲームのように掴まれ運ばれるのは謎のままである。</p>
  <%= image_tag 'tetai.jpg', :size => '400x500',class:"tama3"%>
  </div>

  <div class="balloon5"><br>
  <div class="faceicon">
    <%= image_tag 'hukidasi1.jpg'%> <img~>
  </div>
  <div class="chatting">
    <div class="says">
      <p>うう...怖くて何もできなかった</p>
    </div>
  </div>
</div>
<div class="balloon5">
  <div class="faceicon">
    <%= image_tag 'hukidasi5.jpg'%> <img~>
  </div>
  <div class="chatting">
    <div class="says">
      <p>ごめんね...。まだまだおっきな討伐はダメみたい。</p>
     </div>
    </div>
   </div>
  <div class="h2">
  このでかつよ族はいったい何者...？
  </div>
  <div class="anoko">
  <%= image_tag 'anoko.jpg', :size => '650x550'%> 
  </div>
  <div class="anoko2">
  でかつよ族であるこの怪物の名前は"あの子"。どこから出てきたのか、どんな目的があるのかは不明。<br>
  大きな体と爪でちいかわ達に攻撃を与える危険な存在。<br>
  無邪気な性格をしているためか、面白半分でちいかわ達をもてあそぶシーンが多々ある。<br>
  しかし、この"あの子"にはとある秘密があって、、、！？
  </div>

  <p class="momo">もっとたくさん知りたい人はgood pointのページに飛んでみてね！！</p>
  <%= link_to"good point", chiikawas_good_path,class:"momo2"%>
  


  








 

app/views/chiikawas/suekiti.html.erb
<div class="gatya">
    <p class="tomato">末吉です！！</p>
    <%= image_tag 'suekiti.jpg',:size => '450x400' %> 
</div>
<p class="arice">ちょっといいことあるかな？</p>

app/views/chiikawas/syoukiti.html.erb
<div class="gatya">
    <p class="tomato">小吉です！！</p>
    <%= image_tag 'syoukiti.jpg',:size => '700x500' %> 
</div>
<p class="arice">小さな幸せが見つかるといいね！！</p>

app/views/chiikawas/tyuukiti.html.erb
<div class="gatya">
    <p class="tomato">中吉です！！</p>
    <%= image_tag 'tyuukiti.jpg',:size => '450x500' %> 
</div>
<p class="arice">人助けをするともっと運があがるかも！？</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chiikawa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topic3s/show.html.erb
<link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
<% if @topic3.question3 == 7 %>
<%= link_to"もどる", chiikawas_index_path,class:"mai" %>
<p class="maru">診断結果</p>
<br>
<br>
<br>
<br>
<p class="mese">マイペース...でも資格を持つ優秀な</p>
  <p class="kuri">あなたはくりまんじゅうです！</p>
  <div class="photo">
  <%= image_tag 'chiikawa kuri.jpg',:size => '350x400' %>
  </div>
  
<% end %>

<% if @topic3.question3 == 8 %>
<%= link_to"もどる", chiikawas_index_path,class:"mai" %>
<p class="maru">診断結果</p>
<br>
<br>
<br>
<br>
<p class="mese">全ては自分のペースで突き進む！そんな</p>
  <p class="kuri">あなたはうさぎです！</p>
  <div class="photo">
  <%= image_tag 'chiikawa characters z.jpg',:size => '300x400' %>
  </div>
<% end %>

<% if @topic3.question3 == 9 %>
<%= link_to"もどる", chiikawas_index_path %>
<p class="maru">診断結果</p>
<br>
<br>
<br>
<br>
<p class="mese">最高にポジティブ!ナイスガイな</p>
  <p class="kuri">あなたはハチワレです！</p>
  <div class="photo">
  <%= image_tag 'chiikawa characters zz.jpg',:size => '350x450' %>
  </div>
<% end %>

<% if @topic3.question3 == 10 %>
<%= link_to"もどる", chiikawas_index_path,class:"mai" %>
<p class="maru">診断結果</p>
<br>
<br>
<br>
<br>
<p class="mese">慎重で確実な道を進む</p>
  <p class="kuri">あなたは鎧さんです！</p>
  <div class="photo">
  <%= image_tag 'yororisan.jpg',:size => '300x650' %>
  </div>
<% end %>

<% if @topic3.question3 == 11 %>
<%= link_to"もどる", chiikawas_index_path,class:"mai" %>
<p class="maru">診断結果</p>
<br>
<br>
<br>
<br>
<p class="mese">勇敢で兄貴・姉御肌の</p>
  <p class="kuri">あなたはラッコです！</p>
  <div class="photo">
  <%= image_tag 'chiikawa rako.jpg',:size => '300x400' %>
  </div>
<% end %>

<% if @topic3.question3 == 12 %>
<%= link_to"もどる", chiikawas_index_path,class:"mai" %>
<p class="maru">診断結果</p>
<br>
<br>
<br>
<br>
<p class="mese">末っ子タイプ、でもやるときはやるそんな</p>
  <p class="kuri">あなたはちいかわです！</p>
  <div class="photo">
  <%= image_tag 'chiikawa characters zzz.jpg',:size => '350x400' %>
  </div>
<% end %>

<% if @topic3.question3 == 13 %>
<%= link_to"もどる", chiikawas_index_path,class:"mai" %>
<p class="maru">診断結果</p>
<br>
<br>
<br>
<br>
<p class="mese">自由であり、自信のある</p>
  <p class="kuri">あなたはモモンガです！</p>
  <div class="photo">
  <%= image_tag 'chiikawa momonga.jpg',:size => '370x400' %>
  </div>
<% end %>

<% if @topic3.question3 == 14 %>
<%= link_to"もどる", chiikawas_index_path,class:"mai" %>
<p class="maru">診断結果</p>
<br>
<br>
<br>
<br>
<p class="mese">おっとりしてて謙虚、そんな</p>
  <p class="kuri">あなたはカニちゃん（古本屋さん）です！</p>
  <div class="photo">
  <%= image_tag 'kanichan.jpg',:size => '400x500' %>
  </div>
<% end %>